### ISSUE TITLE
Can we add Convieneince Methods on Bidirectional Assocations

### ISSUE THREAD

**Issue by JaCkIsO** [CS544-EA-TEAM-8/meditation-attendance-project#15]
Refer to Module 03 slide from lectures
Eg. Faculty and CourseOffering

**Comment by kasimebrahim** [comment]
@JaCkIsO does #16 take care of this?

CourseOffering is created only from Course b/c without a course there is no offering. and the Facility is also passed and the offering is added to the facility.

**Comment by JaCkIsO** [comment]
It does I'll go ahead and close it
